__author__ = 'NamelessOne'


class CrashReport:
    def __init__(self, parameters):
        self.report_id = parameters.getvalue('REPORT_ID', "")
        self.app_version_code = parameters.getvalue('APP_VERSION_CODE', "")
        self.app_version_name = parameters.getvalue('APP_VERSION_NAME', "")
        self.package_name = parameters.getvalue('PACKAGE_NAME', "")
        self.file_path = parameters.getvalue('FILE_PATH', "")
        self.phone_model = parameters.getvalue('PHONE_MODEL', "")
        self.brand = parameters.getvalue('BRAND', "")
        self.product = parameters.getvalue('PRODUCT', "")
        self.android_version = parameters.getvalue('ANDROID_VERSION', "")
        self.build = parameters.getvalue('BUILD', "")
        self.total_mem_size = parameters.getvalue('TOTAL_MEM_SIZE', "")
        self.available_mem_size = parameters.getvalue('AVAILABLE_MEM_SIZE', "")
        self.custom_data = parameters.getvalue('CUSTOM_DATA', "")
        self.is_silent = parameters.getvalue('IS_SILENT', "")
        self.stack_trace = parameters.getvalue('STACK_TRACE', "")
        self.initial_configuration = parameters.getvalue('INITIAL_CONFIGURATION', "")
        self.crash_configuration = parameters.getvalue('CRASH_CONFIGURATION', "")
        self.display = parameters.getvalue('DISPLAY', "")
        self.user_comment = parameters.getvalue('USER_COMMENT', "")
        self.user_email = parameters.getvalue('USER_EMAIL', "")
        self.user_app_start_date = parameters.getvalue('USER_APP_START_DATE', "")
        self.user_crash_date = parameters.getvalue('USER_CRASH_DATE', "")
        self.dumpsys_meminfo = parameters.getvalue('DUMPSYS_MEMINO', "")
        self.logcat = parameters.getvalue('LOGCAT', "")
        self.installation_id = parameters.getvalue('INSTALLATION_ID', "")
        self.device_features = parameters.getvalue('DEVICE_EATURES', "")
        self.environment = parameters.getvalue('ENVIRONMENT', "")
        self.shared_preferences = parameters.getvalue('SHARED_PREFERENCES', "")
        self.settings_system = parameters.getvalue('SETTINGS_SYSTEM', "")
        self.settings_secure = parameters.getvalue('SETTINGS_SECURE', "")